title: Ph.D. Juan S. Cruz # your name (or website title) here
logo: "/images/ProfileHeadshot_circle.jpg?raw=true" # your photo (or logo) here
description: # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist with background in theoretical physics. Bringing all the expertise of years in academia, together with fresh perspectives and cutting edge tools to the financial sector.
  <br><br>
  I have over 6 years of specialized quantitative and analytical skills coming from a highly competitive academic environment and am always eager to solve problems using modern data science tools.
linkedin_url: "https://www.linkedin.com/in/juan-s-cruz-phd-46321b116"
orcid_url: "https://orcid.org/0000-0002-4310-6361"
github_repository: "https://github.com/juan-s-cruz/"
remote_theme: pages-themes/cayman@v0.2.0

# === For local development only ===
# theme: jekyll-theme-cayman
# sass:
#   load_paths:
#     - _sass
#     - assets/css

plugins:
  - jekyll-remote-theme

